version: 0.2

phases:
  build:
    commands:
      - ./gradlew assembleDebug
  post_build:
    commands:
      - echo Build completed successfully   
artifacts:
  files:
    - target/book-management-service.jar
  discard-paths: yes