version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - gradle build
  post_build:
    commands:
      - echo Build completed successfully   
artifacts:
  files:
    - 'build/libs/*.jar'
  discard-paths: yes